name: Deploy AppGyver Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Aciona o deploy quando houver push na branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"  # Token padrão do GitHub
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live   # "live" publica diretamente; você pode usar "preview" se quiser testar
        projectId: acampdeep

